language: rust
rust:
  - nightly

cache:
  - cargo

addons:
  apt:
    packages:
      - python3-pip
      - python3-dev

install:
  - rustup component add rustfmt
  - cargo install form || true
  - cargo install svd2rust || true
  - cargo install atdf2svd || true
  - python3 -c "__import__('yaml')" || pip3 install --user pyyaml

script:
  - make
  - cargo build --all-features
