language: rust
rust:
  - nightly-2020-10-25

cache:
  cargo: true
  pip: true
  directories:
    - /opt/pyenv
    - ~/svd2rust

install:
  - pyenv install 3.6.3
  - pyenv global 3.6.3
  - python3 -c "__import__('svdtools')" || pip3 install --user svdtools
  - rustup component add rustfmt
  - cargo install form || true
  # TODO: Hack to use the latest version of svd2rust
  # - cargo install svd2rust || true
  - ! test -d svd2rust || (mkdir svd2rust && cd svd2rust && git init && git remote add origin https://github.com/rust-embedded/svd2rust.git)
  - (cd svd2rust && git fetch origin 56be78729279eeebef65110c13be8d96c0b9270f && git checkout FETCH_HEAD && cargo install --path .)
  - cargo install atdf2svd || true

script:
  - pyenv global 3.6.3
  - make RUSTUP_TOOLCHAIN=nightly-2020-10-25
  - cargo build --all-features
